//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::SimpleObject;
use async_trait::async_trait;
use nanoid::nanoid;
use sea_orm::{ActiveValue, entity::prelude::*};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject)]
#[sea_orm(table_name = "access_link")]
#[graphql(name = "AccessLink")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: String,
    pub name: String,
    pub created_on: DateTimeUtc,
    #[graphql(skip)]
    pub issued_tokens: Vec<String>,
    pub expires_on: Option<DateTimeUtc>,
    pub times_used: i32,
    pub maximum_uses: Option<i32>,
    pub is_revoked: Option<bool>,
    pub is_account_default: Option<bool>,
    pub is_mutation_allowed: Option<bool>,
    #[graphql(skip)]
    pub user_id: String,
    pub redirect_to: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.id = ActiveValue::Set(format!("acl_{}", nanoid!(12)));
        }
        Ok(self)
    }
}
