//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use enum_models::{
    ExerciseEquipment, ExerciseForce, ExerciseLevel, ExerciseLot, ExerciseMechanic, ExerciseMuscle,
    ExerciseSource,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "enriched_user_to_exercise")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub lot: ExerciseLot,
    pub level: ExerciseLevel,
    pub force: ExerciseForce,
    pub source: ExerciseSource,
    pub user_id: Option<String>,
    pub exercise_id: Option<String>,
    pub description: Option<String>,
    pub muscles: Vec<ExerciseMuscle>,
    pub num_times_interacted: Option<i32>,
    pub created_by_user_id: Option<String>,
    pub mechanic: Option<ExerciseMechanic>,
    pub equipment: Option<ExerciseEquipment>,
    pub last_updated_on: Option<DateTimeUtc>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
