//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use enum_models::{EntityLot, EntityTranslationVariant};
use media_models::{PodcastTranslationExtraInformation, ShowTranslationExtraInformation};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Serialize, Deserialize, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "entity_translation")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
    pub language: String,
    pub entity_id: String,
    pub value: Option<String>,
    pub entity_lot: EntityLot,
    pub created_on: DateTimeUtc,
    pub person_id: Option<String>,
    pub metadata_id: Option<String>,
    pub variant: EntityTranslationVariant,
    pub metadata_group_id: Option<String>,
    #[sea_orm(column_type = "Json")]
    pub show_extra_information: Option<ShowTranslationExtraInformation>,
    #[sea_orm(column_type = "Json")]
    pub podcast_extra_information: Option<PodcastTranslationExtraInformation>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        on_update = "Cascade",
        on_delete = "Cascade",
        from = "Column::MetadataId",
        to = "super::metadata::Column::Id",
        belongs_to = "super::metadata::Entity"
    )]
    Metadata,
    #[sea_orm(
        on_update = "Cascade",
        on_delete = "Cascade",
        from = "Column::MetadataGroupId",
        to = "super::metadata_group::Column::Id",
        belongs_to = "super::metadata_group::Entity"
    )]
    MetadataGroup,
    #[sea_orm(
        on_update = "Cascade",
        on_delete = "Cascade",
        from = "Column::PersonId",
        to = "super::person::Column::Id",
        belongs_to = "super::person::Entity"
    )]
    Person,
}

impl Related<super::metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metadata.def()
    }
}

impl Related<super::metadata_group::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MetadataGroup.def()
    }
}

impl Related<super::person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Person.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
