//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use async_graphql::{InputObject, Result, SimpleObject};
use common_models::EntityAssets;
use enum_models::{
    ExerciseEquipment, ExerciseForce, ExerciseLevel, ExerciseLot, ExerciseMechanic, ExerciseMuscle,
    ExerciseSource,
};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Eq,
    Hash,
    Clone,
    Debug,
    Default,
    PartialEq,
    Serialize,
    InputObject,
    Deserialize,
    SimpleObject,
    DeriveEntityModel,
)]
#[sea_orm(table_name = "exercise")]
#[graphql(name = "Exercise", input_name = "ExerciseInput")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub lot: ExerciseLot,
    pub level: ExerciseLevel,
    #[sea_orm(column_type = "Json")]
    pub assets: EntityAssets,
    pub source: ExerciseSource,
    pub instructions: Vec<String>,
    pub force: Option<ExerciseForce>,
    pub muscles: Vec<ExerciseMuscle>,
    #[graphql(skip)]
    pub aggregated_instructions: String,
    #[graphql(skip_input)]
    pub created_by_user_id: Option<String>,
    pub mechanic: Option<ExerciseMechanic>,
    pub equipment: Option<ExerciseEquipment>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_to_entity::Entity")]
    CollectionToEntity,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedByUserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(has_many = "super::user_to_entity::Entity")]
    UserToEntity,
}

impl Related<super::collection_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionToEntity.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::user_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserToEntity.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
