//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

pub mod prelude;

pub mod access_link;
pub mod application_cache;
pub mod calendar_event;
pub mod collection;
pub mod collection_entity_membership;
pub mod collection_to_entity;
pub mod daily_user_activity;
pub mod enriched_user_to_metadata;
pub mod exercise;
pub mod functions;
pub mod genre;
pub mod import_report;
pub mod integration;
pub mod metadata;
pub mod metadata_group;
pub mod metadata_group_to_person;
pub mod metadata_to_genre;
pub mod metadata_to_metadata;
pub mod metadata_to_metadata_group;
pub mod metadata_to_person;
pub mod notification_platform;
pub mod person;
pub mod review;
pub mod seen;
pub mod user;
pub mod user_measurement;
pub mod user_to_entity;
pub mod workout;
pub mod workout_template;
