//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use async_trait::async_trait;
use chrono::NaiveDate;
use common_models::EntityAssets;
use enum_models::{MediaLot, MediaSource};
use media_models::{
    AnimeSpecifics, AudioBookSpecifics, BookSpecifics, MangaSpecifics, MetadataExternalIdentifiers,
    MetadataFreeCreator, MovieSpecifics, MusicSpecifics, PodcastSpecifics, ShowSpecifics,
    VideoGameSpecifics, VisualNovelSpecifics, WatchProvider,
};
use nanoid::nanoid;
use rust_decimal::Decimal;
use sea_orm::{ActiveValue, entity::prelude::*};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub lot: MediaLot,
    pub title: String,
    pub identifier: String,
    pub source: MediaSource,
    #[sea_orm(column_type = "Json")]
    pub assets: EntityAssets,
    pub is_nsfw: Option<bool>,
    pub created_on: DateTimeUtc,
    pub is_partial: Option<bool>,
    pub publish_year: Option<i32>,
    pub source_url: Option<String>,
    pub description: Option<String>,
    pub last_updated_on: DateTimeUtc,
    pub publish_date: Option<NaiveDate>,
    pub provider_rating: Option<Decimal>,
    pub original_language: Option<String>,
    pub production_status: Option<String>,
    pub created_by_user_id: Option<String>,
    pub book_specifics: Option<BookSpecifics>,
    pub show_specifics: Option<ShowSpecifics>,
    pub anime_specifics: Option<AnimeSpecifics>,
    pub manga_specifics: Option<MangaSpecifics>,
    pub music_specifics: Option<MusicSpecifics>,
    pub movie_specifics: Option<MovieSpecifics>,
    pub podcast_specifics: Option<PodcastSpecifics>,
    #[sea_orm(column_type = "Json")]
    pub watch_providers: Option<Vec<WatchProvider>>,
    #[sea_orm(column_type = "Json")]
    pub free_creators: Option<Vec<MetadataFreeCreator>>,
    pub audio_book_specifics: Option<AudioBookSpecifics>,
    pub video_game_specifics: Option<VideoGameSpecifics>,
    pub visual_novel_specifics: Option<VisualNovelSpecifics>,
    #[sea_orm(column_type = "Json")]
    pub external_identifiers: Option<MetadataExternalIdentifiers>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::calendar_event::Entity")]
    CalendarEvent,
    #[sea_orm(has_many = "super::collection_to_entity::Entity")]
    CollectionToEntity,
    #[sea_orm(has_many = "super::entity_to_entity::Entity")]
    EntityToEntity,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::seen::Entity")]
    Seen,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedByUserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
    #[sea_orm(has_many = "super::user_to_entity::Entity")]
    UserToEntity,
}

impl Related<super::calendar_event::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CalendarEvent.def()
    }
}

impl Related<super::collection_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionToEntity.def()
    }
}

impl Related<super::entity_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EntityToEntity.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::seen::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Seen.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::user_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserToEntity.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.id = ActiveValue::Set(format!("met_{}", nanoid!(12)));
        }
        Ok(self)
    }
}
