//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use async_graphql::SimpleObject;
use async_trait::async_trait;
use chrono::NaiveDate;
use common_models::{EntityAssets, PersonSourceSpecifics};
use enum_models::MediaSource;
use media_models::PersonStateChanges;
use nanoid::nanoid;
use sea_orm::{ActiveValue, entity::prelude::*};
use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;

#[skip_serializing_none]
#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, SimpleObject)]
#[graphql(name = "Person")]
#[sea_orm(table_name = "person")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub identifier: String,
    pub source: MediaSource,
    #[sea_orm(column_type = "Json")]
    pub assets: EntityAssets,
    pub place: Option<String>,
    pub gender: Option<String>,
    pub created_on: DateTimeUtc,
    pub website: Option<String>,
    pub is_partial: Option<bool>,
    pub source_url: Option<String>,
    pub description: Option<String>,
    pub last_updated_on: DateTimeUtc,
    pub associated_entity_count: i32,
    pub birth_date: Option<NaiveDate>,
    pub death_date: Option<NaiveDate>,
    pub associated_metadata_count: i32,
    pub created_by_user_id: Option<String>,
    pub alternate_names: Option<Vec<String>>,
    pub associated_metadata_groups_count: i32,
    #[graphql(skip)]
    pub state_changes: Option<PersonStateChanges>,
    #[graphql(skip)]
    pub source_specifics: Option<PersonSourceSpecifics>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_to_entity::Entity")]
    CollectionToEntity,
    #[sea_orm(has_many = "super::metadata_group_to_person::Entity")]
    MetadataGroupToPerson,
    #[sea_orm(has_many = "super::metadata_to_person::Entity")]
    MetadataToPerson,
    #[sea_orm(has_many = "super::review::Entity")]
    Review,
    #[sea_orm(has_many = "super::user_to_entity::Entity")]
    UserToEntity,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::CreatedByUserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    User,
}

impl Related<super::collection_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionToEntity.def()
    }
}

impl Related<super::metadata_group_to_person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MetadataGroupToPerson.def()
    }
}

impl Related<super::metadata_to_person::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MetadataToPerson.def()
    }
}

impl Related<super::review::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Review.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::user_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserToEntity.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.id = ActiveValue::Set(format!("per_{}", nanoid!(12)));
        }
        Ok(self)
    }
}
