//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use async_graphql::{Result, SimpleObject};
use fitness_models::{WorkoutInformation, WorkoutSummary};
use schematic::Schematic;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};
use serde_with::skip_serializing_none;

/// A workout that was completed by the user.
#[skip_serializing_none]
#[derive(
    Eq,
    Clone,
    Debug,
    Default,
    Schematic,
    Serialize,
    PartialEq,
    Deserialize,
    SimpleObject,
    DeriveEntityModel,
)]
#[sea_orm(table_name = "workout")]
#[graphql(name = "Workout")]
#[schematic(rename = "Workout", rename_all = "snake_case")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub name: String,
    pub duration: i32,
    #[graphql(skip)]
    #[serde(skip)]
    pub user_id: String,
    pub end_time: DateTimeUtc,
    pub start_time: DateTimeUtc,
    pub summary: WorkoutSummary,
    pub template_id: Option<String>,
    pub repeated_from: Option<String>,
    pub information: WorkoutInformation,
    pub calories_burnt: Option<Decimal>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::collection_to_entity::Entity")]
    CollectionToEntity,
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
    #[sea_orm(
        belongs_to = "Entity",
        from = "Column::RepeatedFrom",
        to = "Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    RepeatedFrom,
    #[sea_orm(
        belongs_to = "super::workout_template::Entity",
        from = "Column::TemplateId",
        to = "super::workout_template::Column::Id",
        on_update = "Cascade",
        on_delete = "SetNull"
    )]
    WorkoutTemplate,
}

impl Related<super::collection_to_entity::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CollectionToEntity.def()
    }
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl Related<super::workout_template::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkoutTemplate.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
