import {
	Archive,
	ArrowRight,
	ArrowUpDown,
	Book,
	BookCopy,
	BookHeart,
	BookImage,
	BookMarked,
	BookOpen,
	Bookmark,
	Box,
	Building2,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleAlert,
	CircleCheck,
	CircleX,
	Clapperboard,
	ClipboardList,
	Clock,
	Copy,
	Crown,
	Disc3,
	Download,
	Dumbbell,
	FileText,
	Film,
	FlaskConical,
	Folder,
	FolderKanban,
	Folders,
	Gamepad2,
	Globe,
	Grid2X2,
	GripVertical,
	Headphones,
	Heart,
	HeartPulse,
	House,
	Image,
	Inbox,
	Info,
	Joystick,
	Layers3,
	Library,
	List,
	ListVideo,
	Lock,
	LogOut,
	Menu,
	Mic,
	Monitor,
	MonitorPlay,
	Moon,
	MoreHorizontal,
	Music2,
	PanelLeft,
	Plus,
	Podcast,
	Puzzle,
	Radio,
	RotateCcw,
	Ruler,
	Search,
	SearchX,
	Settings,
	SlidersHorizontal,
	Sparkles,
	SquarePlay,
	Star,
	Sun,
	Table2,
	Tags,
	Trash2,
	Tv,
	Upload,
	UserCircle,
	Users,
	X,
	Zap,
} from "lucide-react";

const icons = {
	x: X,
	tv: Tv,
	box: Box,
	mic: Mic,
	sun: Sun,
	zap: Zap,
	book: Book,
	copy: Copy,
	film: Film,
	info: Info,
	list: List,
	lock: Lock,
	menu: Menu,
	moon: Moon,
	plus: Plus,
	star: Star,
	tags: Tags,
	home: House,
	check: Check,
	clock: Clock,
	crown: Crown,
	globe: Globe,
	heart: Heart,
	house: House,
	image: Image,
	inbox: Inbox,
	radio: Radio,
	ruler: Ruler,
	users: Users,
	grid: Grid2X2,
	music: Music2,
	table: Table2,
	folder: Folder,
	logout: LogOut,
	puzzle: Puzzle,
	search: Search,
	upload: Upload,
	"disc-3": Disc3,
	archive: Archive,
	folders: Folders,
	library: Library,
	monitor: Monitor,
	podcast: Podcast,
	user: UserCircle,
	"music-2": Music2,
	"trash-2": Trash2,
	bookmark: Bookmark,
	download: Download,
	dumbbell: Dumbbell,
	joystick: Joystick,
	settings: Settings,
	sparkles: Sparkles,
	"circle-x": CircleX,
	"layers-3": Layers3,
	"search-x": SearchX,
	"book-copy": BookCopy,
	"book-open": BookOpen,
	"file-text": FileText,
	"gamepad-2": Gamepad2,
	headphones: Headphones,
	"book-heart": BookHeart,
	"book-image": BookImage,
	"building-2": Building2,
	"chevron-up": ChevronUp,
	"list-video": ListVideo,
	"panel-left": PanelLeft,
	"rotate-ccw": RotateCcw,
	"arrow-right": ArrowRight,
	"book-marked": BookMarked,
	"heart-pulse": HeartPulse,
	"play-square": SquarePlay,
	"square-play": SquarePlay,
	clapperboard: Clapperboard,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"circle-alert": CircleAlert,
	"circle-check": CircleCheck,
	"monitor-play": MonitorPlay,
	"arrow-up-down": ArrowUpDown,
	"chevron-right": ChevronRight,
	"flask-conical": FlaskConical,
	"folder-kanban": FolderKanban,
	"grip-vertical": GripVertical,
	"clipboard-list": ClipboardList,
	"more-horizontal": MoreHorizontal,
	"sliders-horizontal": SlidersHorizontal,
};

type AppIconProps = {
	readonly name: string;
	readonly size?: number;
	readonly className?: string;
};

const isIconName = (name: string): name is keyof typeof icons => Object.hasOwn(icons, name);

export function AppIcon({ name, size = 16, className }: AppIconProps) {
	const known = isIconName(name);
	const Icon = known ? icons[name] : Circle;
	return (
		<Icon
			size={size}
			focusable="false"
			strokeWidth={1.7}
			aria-hidden="true"
			className={className}
			data-app-icon={known ? name : "fallback"}
		/>
	);
}
