type SandboxScriptKey = "getCachedValue" | "httpCall" | "setCachedValue";

export type BuiltinSandboxScript = {
	readonly slug: string;
	readonly code: string;
	readonly allowedHostFunctions: ReadonlyArray<SandboxScriptKey>;
};

const audibleAudiobookScript = [
	"const SEARCH_CACHE_TTL_SECONDS = 300;",
	"const DETAILS_CACHE_TTL_SECONDS = 3600;",
	'const AUDIBLE_BASE_URL = "https://api.audible.com/1.0/catalog/products";',
	"",
	"const parseJsonResponse = (body) => {",
	"  try {",
	"    return JSON.parse(body);",
	"  } catch {",
	'    throw new Error("Audible returned invalid JSON");',
	"  }",
	"};",
	"",
	"const sanitizeText = (value) => {",
	'  if (typeof value !== "string") {',
	"    return null;",
	"  }",
	"  const trimmed = value.trim();",
	"  return trimmed ? trimmed : null;",
	"};",
	"",
	"const stripHtml = (value) => {",
	"  const text = sanitizeText(value);",
	'  return text ? text.replace(/<[^>]+>/g, " ").replace(/\\s+/g, " ").trim() : null;',
	"};",
	"",
	"const parseContributorName = (value) => {",
	'  if (!value || typeof value !== "object") {',
	"    return null;",
	"  }",
	"  return sanitizeText(value.name);",
	"};",
	"",
	"const parseProductAuthor = (product) => {",
	"  const authors = Array.isArray(product?.authors) ? product.authors : [];",
	"  for (const author of authors) {",
	"    const name = parseContributorName(author);",
	"    if (name) {",
	"      return name;",
	"    }",
	"  }",
	"  return null;",
	"};",
	"",
	"const parseNarrators = (product) => {",
	"  const narrators = Array.isArray(product?.narrators) ? product.narrators : [];",
	"  return narrators",
	"    .map((narrator) => parseContributorName(narrator))",
	'    .filter((name) => typeof name === "string");',
	"};",
	"",
	"const parseImageUrl = (product) =>",
	'  sanitizeText(product?.product_images?.["500"] ?? product?.product_images?.["2400"] ?? null);',
	"",
	"const parseSourceUrl = (product, asin) =>",
	'  sanitizeText(product?.product_urls?.desktop ?? null) ?? "https://www.audible.com/pd/" + asin;',
	"",
	"const getCachedJson = async (key) => {",
	"  const cached = await getCachedValue(key);",
	'  return typeof cached === "string" && cached.trim() ? parseJsonResponse(cached) : null;',
	"};",
	"",
	"const setCachedJson = async (key, value, ttlSeconds) => {",
	"  await setCachedValue(key, JSON.stringify(value), ttlSeconds);",
	"};",
	"",
	'driver("search", async function (context) {',
	"  const query = sanitizeText(context?.query);",
	"  if (!query) {",
	'    throw new Error("query is required");',
	"  }",
	"",
	"  const page = Number.isFinite(Number(context?.page)) ? Math.max(1, Math.floor(Number(context.page))) : 1;",
	"  const pageSize = Number.isFinite(Number(context?.pageSize))",
	"    ? Math.max(1, Math.min(10, Math.floor(Number(context.pageSize))))",
	"    : 3;",
	"",
	'  const cacheKey = "reference:audible:search:" + query.toLowerCase() + ":" + page + ":" + pageSize;',
	"  const cached = await getCachedJson(cacheKey);",
	"  if (cached) {",
	"    return cached;",
	"  }",
	"",
	"  const params = new URLSearchParams({",
	"    title: query,",
	"    num_results: String(pageSize),",
	"    page: String(page - 1),",
	'    products_sort_by: "Relevance",',
	'    response_groups: "contributors,media,product_attrs",',
	"  });",
	"",
	'  const response = await httpCall("GET", AUDIBLE_BASE_URL + "?" + params.toString());',
	"  if (!response?.success) {",
	'    throw new Error(response?.error ?? "Audible search request failed");',
	"  }",
	"",
	"  const payload = parseJsonResponse(response.data.body);",
	"  const products = Array.isArray(payload?.products) ? payload.products : [];",
	"  const items = products",
	"    .map((product) => {",
	"      const externalId = sanitizeText(product?.asin);",
	"      const title = sanitizeText(product?.title);",
	"      if (!externalId || !title) {",
	"        return null;",
	"      }",
	"",
	"      return {",
	"        author: parseProductAuthor(product),",
	"        title,",
	"        imageUrl: parseImageUrl(product),",
	"        externalId,",
	"      };",
	"    })",
	"    .filter((item) => item !== null);",
	"",
	"  const result = { items };",
	"  await setCachedJson(cacheKey, result, SEARCH_CACHE_TTL_SECONDS);",
	"  return result;",
	"});",
	"",
	'driver("details", async function (context) {',
	"  const externalId = sanitizeText(context?.externalId);",
	"  if (!externalId) {",
	'    throw new Error("externalId is required");',
	"  }",
	"",
	'  const cacheKey = "reference:audible:details:" + externalId;',
	"  const cached = await getCachedJson(cacheKey);",
	"  if (cached) {",
	"    return cached;",
	"  }",
	"",
	"  const params = new URLSearchParams({",
	'    image_sizes: "500",',
	'    response_groups: "contributors,media,product_attrs,product_extended_attrs,series",',
	"  });",
	"",
	'  const response = await httpCall("GET", AUDIBLE_BASE_URL + "/" + externalId + "?" + params.toString());',
	"  if (!response?.success) {",
	'    throw new Error(response?.error ?? "Audible details request failed");',
	"  }",
	"",
	"  const payload = parseJsonResponse(response.data.body);",
	"  const product = payload?.product;",
	'  if (!product || typeof product !== "object") {',
	'    throw new Error("Audible returned no product data");',
	"  }",
	"",
	"  const title = sanitizeText(product.title);",
	"  if (!title) {",
	'    throw new Error("Audible product is missing title");',
	"  }",
	"",
	"  const result = {",
	"    asin: externalId,",
	"    author: parseProductAuthor(product),",
	"    title,",
	"    narrators: parseNarrators(product),",
	"    imageUrl: parseImageUrl(product),",
	"    sourceUrl: parseSourceUrl(product, externalId),",
	"    description: stripHtml(product?.publisher_summary ?? product?.merchandising_summary ?? null),",
	"  };",
	"",
	"  await setCachedJson(cacheKey, result, DETAILS_CACHE_TTL_SECONDS);",
	"  return result;",
	"});",
].join("\n");

const builtinScripts = [
	{
		allowedHostFunctions: ["getCachedValue", "httpCall", "setCachedValue"],
		code: audibleAudiobookScript,
		slug: "audiobook.audible",
	},
] satisfies ReadonlyArray<BuiltinSandboxScript>;

export const listBuiltinSandboxScripts = () => builtinScripts;

export const getBuiltinSandboxScript = (slug: string) =>
	builtinScripts.find((script) => script.slug === slug);
