{{- if and .Values.postgres.enabled (not .Values.postgres.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ryot.postgres.fullname" . }}
  labels:
    {{- include "ryot.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
type: Opaque
stringData:
  postgres-password: {{ .Values.postgres.auth.password | quote }}
{{- end }}
