{{- if and .Values.redis.enabled .Values.redis.auth.password (not .Values.redis.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ryot.redis.secretName" . }}
  labels:
    {{- include "ryot.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
type: Opaque
stringData:
  redis-password: {{ .Values.redis.auth.password | quote }}
{{- end }}
