query Collections($input: CollectionInput!) {
  collections(input: $input) {
    collectionDetails {
      id
      name
    }
    mediaDetails {
      identifier
      lot
      title
      image
      publishYear
    }
  }
}
