query Collections($limit: Int) {
  collections(limit: $limit) {
    collectionDetails {
      id
      name
    }
    mediaDetails {
      identifier
      lot
      title
      image
      publishYear
    }
  }
}
