query CollectionContents($input: CollectionContentsInput!) {
  collectionContents(input: $input) {
    user {
      name
    }
    details {
      name
      description
      visibility
    }
    media {
      identifier
      lot
      title
      image
      publishYear
    }
  }
}
