query GetOidcRedirectUrl {
	getOidcRedirectUrl
}

query UserByOidcIssuerId($oidcIssuerId: String!) {
	userByOidcIssuerId(oidcIssuerId: $oidcIssuerId)
}

query GetOidcToken($code: String!) {
	getOidcToken(code: $code) {
		email
		subject
	}
}

query GetPresignedS3Url($key: String!) {
	getPresignedS3Url(key: $key)
}

query UserExports {
	userExports {
		url
		key
		size
		endedAt
		startedAt
	}
}

query UserCollectionsList {
	userCollectionsList {
		cacheId
		response {
			id
			name
			count
			isDefault
			description
			creator {
				id
				name
			}
			collaborators {
				extraInformation {
					isHidden
				}
				collaborator {
					id
					name
				}
			}
			informationTemplate {
				lot
				name
				required
				description
				defaultValue
				possibleValues
			}
		}
	}
}

query UserIntegrations {
	userIntegrations {
		id
		lot
		name
		provider
		createdOn
		isDisabled
		lastFinishedAt
		maximumProgress
		minimumProgress
		syncToOwnedCollection
		extraSettings {
			disableOnContinuousErrors
		}
		triggerResult {
			error
			finishedAt
		}
		providerSpecifics {
			plexYankToken
			plexYankBaseUrl
			plexSinkUsername
			audiobookshelfToken
			audiobookshelfBaseUrl
			komgaBaseUrl
			komgaUsername
			komgaPassword
			komgaProvider
			radarrBaseUrl
			radarrApiKey
			radarrProfileId
			radarrRootFolderPath
			radarrSyncCollectionIds
			radarrTagIds
			sonarrProfileId
			sonarrApiKey
			sonarrBaseUrl
			sonarrRootFolderPath
			sonarrSyncCollectionIds
			sonarrTagIds
			jellyfinPushBaseUrl
			jellyfinPushUsername
			jellyfinPushPassword
			youtubeMusicTimezone
			youtubeMusicAuthCookie
			ryotBrowserExtensionDisabledSites
		}
	}
}

query UserNotificationPlatforms {
	userNotificationPlatforms {
		id
		lot
		createdOn
		isDisabled
		description
		configuredEvents
	}
}

query UsersList($query: String) {
	usersList(query: $query) {
		id
		lot
		name
		isDisabled
	}
}

query UserMetadataRecommendations {
	userMetadataRecommendations {
		cacheId
		response
	}
}

query UserUpcomingCalendarEvents($input: UserUpcomingCalendarEventInput!) {
	userUpcomingCalendarEvents(input: $input) {
		...CalendarEventPart
	}
}

query UserCalendarEvents($input: UserCalendarEventInput!) {
	userCalendarEvents(input: $input) {
		date
		events {
			...CalendarEventPart
		}
	}
}

query UserMetadataGroupsList($input: UserMetadataGroupsListInput!) {
	userMetadataGroupsList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserPeopleList($input: UserPeopleListInput!) {
	userPeopleList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserAccessLinks {
	userAccessLinks {
		id
		name
		createdOn
		expiresOn
		timesUsed
		isRevoked
		maximumUses
		isAccountDefault
		isMutationAllowed
	}
}

query ExerciseDetails($exerciseId: String!) {
	exerciseDetails(exerciseId: $exerciseId) {
		id
		lot
		name
		level
		force
		source
		muscles
		mechanic
		equipment
		instructions
		createdByUserId
		assets {
			...EntityAssetsPart
		}
	}
}

query UserExercisesList($input: UserExercisesListInput!) {
	userExercisesList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserImportReports {
	userImportReports {
		id
		source
		progress
		startedOn
		finishedOn
		wasSuccess
		estimatedFinishTime
		details {
			import {
				total
			}
			failedItems {
				lot
				step
				error
				identifier
			}
		}
	}
}

query UserGenresList($input: SearchInput!) {
	userGenresList(input: $input) {
		items
		details {
			...SearchDetailsPart
		}
	}
}

query GenreDetails($input: GenreDetailsInput!) {
	genreDetails(input: $input) {
		response {
			details {
				id
				name
				numItems
			}
			contents {
				details {
					...SearchDetailsPart
				}
				items
			}
		}
	}
}

query CollectionContents($input: CollectionContentsInput!) {
	collectionContents(input: $input) {
		cacheId
		response {
			totalItems
			user {
				id
				name
			}
			reviews {
				...ReviewItemPart
			}
			details {
				name
				createdOn
				description
			}
			results {
				details {
					...SearchDetailsPart
				}
				items {
					entityId
					entityLot
				}
			}
		}
	}
}

query MetadataGroupDetails($metadataGroupId: String!) {
	metadataGroupDetails(metadataGroupId: $metadataGroupId) {
		response {
			contents
			details {
				id
				lot
				title
				parts
				source
				isPartial
				sourceUrl
				identifier
				description
				assets {
					...EntityAssetsPart
				}
			}
		}
	}
}

query MetadataGroupSearch($input: MetadataGroupSearchInput!) {
	metadataGroupSearch(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserMetadataList($input: UserMetadataListInput!) {
	userMetadataList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query MetadataSearch($input: MetadataSearchInput!) {
	metadataSearch(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query PeopleSearch($input: PeopleSearchInput!) {
	peopleSearch(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserMetadataGroupDetails($metadataGroupId: String!) {
	userMetadataGroupDetails(metadataGroupId: $metadataGroupId) {
		response {
			hasInteracted
			averageRating
			isRecentlyConsumed
			reviews {
				...ReviewItemPart
			}
			collections {
				...CollectionToEntityDetailsPart
			}
		}
	}
}

query UserPersonDetails($personId: String!) {
	userPersonDetails(personId: $personId) {
		response {
			hasInteracted
			averageRating
			isRecentlyConsumed
			collections {
				...CollectionToEntityDetailsPart
			}
			reviews {
				...ReviewItemPart
			}
		}
	}
}

query UserWorkoutDetails($workoutId: String!) {
	userWorkoutDetails(workoutId: $workoutId) {
		metadataConsumed
		collections {
			...CollectionToEntityDetailsPart
		}
		details {
			id
			name
			endTime
			duration
			startTime
			templateId
			repeatedFrom
			caloriesBurnt
			summary {
				...WorkoutSummaryPart
			}
			information {
				...WorkoutInformationPart
			}
		}
	}
}

query UserWorkoutsList($input: UserTemplatesOrWorkoutsListInput!) {
	userWorkoutsList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserWorkoutTemplateDetails($workoutTemplateId: String!) {
	userWorkoutTemplateDetails(workoutTemplateId: $workoutTemplateId) {
		collections {
			...CollectionToEntityDetailsPart
		}
		details {
			id
			name
			createdOn
			summary {
				...WorkoutSummaryPart
			}
			information {
				...WorkoutInformationPart
			}
		}
	}
}

query UserWorkoutTemplatesList($input: UserTemplatesOrWorkoutsListInput!) {
	userWorkoutTemplatesList(input: $input) {
		cacheId
		response {
			items
			details {
				...SearchDetailsPart
			}
		}
	}
}

query UserAnalyticsParameters {
	userAnalyticsParameters {
		cacheId
		response {
			endDate
			startDate
		}
	}
}

query TrendingMetadata {
	trendingMetadata
}

query CollectionRecommendations($input: CollectionRecommendationsInput!) {
	collectionRecommendations(input: $input) {
		items
		details {
			...SearchDetailsPart
		}
	}
}

query MetadataLookup($title: String!) {
	metadataLookup(title: $title) {
		cacheId
		response {
			... on MetadataLookupFoundResult {
				data {
					lot
					source
					identifier
				}
				showInformation {
					season
					episode
				}
			}
			... on MetadataLookupNotFound {
				notFound
			}
		}
	}
}
