query GetOidcRedirectUrl {
	getOidcRedirectUrl
}

query UserByOidcIssuerId($oidcIssuerId: String!) {
	userByOidcIssuerId(oidcIssuerId: $oidcIssuerId)
}

query GetOidcToken($code: String!) {
	getOidcToken(code: $code) {
		subject
		email
	}
}

query GetPresignedS3Url($key: String!) {
	getPresignedS3Url(key: $key)
}

query ProvidersLanguageInformation {
	providersLanguageInformation {
		supported
		default
		source
	}
}

query UserExports {
	userExports {
		url
		size
		endedAt
		startedAt
	}
}

query UserCollectionsList($name: String) {
	userCollectionsList(name: $name) {
		id
		name
		count
		isDefault
		description
		creator {
			id
			name
		}
		collaborators {
			id
			name
		}
		informationTemplate {
			lot
			name
			required
			description
			defaultValue
		}
	}
}

query UserIntegrations {
	userIntegrations {
		id
		lot
		provider
		createdOn
		isDisabled
		maximumProgress
		minimumProgress
		lastTriggeredOn
		syncToOwnedCollection
	}
}

query UserNotificationPlatforms {
	userNotificationPlatforms {
		id
		lot
		createdOn
		isDisabled
		description
	}
}

query UsersList($query: String) {
	usersList(query: $query) {
		id
		lot
		name
		isDisabled
	}
}

query UserRecommendations {
	userRecommendations
}

query UserUpcomingCalendarEvents($input: UserUpcomingCalendarEventInput!) {
	userUpcomingCalendarEvents(input: $input) {
		...CalendarEventPart
	}
}

query UserCalendarEvents($input: UserCalendarEventInput!) {
	userCalendarEvents(input: $input) {
		date
		events {
			...CalendarEventPart
		}
	}
}

query MetadataPartialDetails($metadataId: String!) {
	metadataPartialDetails(metadataId: $metadataId) {
		id
		lot
		title
		image
		publishYear
	}
}

query MetadataGroupsList($input: MetadataGroupsListInput!) {
	metadataGroupsList(input: $input) {
		details {
			total
			nextPage
		}
		items
	}
}

query PeopleList($input: PeopleListInput!) {
	peopleList(input: $input) {
		details {
			total
			nextPage
		}
		items
	}
}

query UserAccessLinks {
	userAccessLinks {
		id
		name
		isDemo
		createdOn
		expiresOn
		timesUsed
		isRevoked
		maximumUses
		isAccountDefault
		isMutationAllowed
	}
}

query DailyUserActivities($input: DailyUserActivitiesInput!) {
	dailyUserActivities(input: $input) {
		groupedBy
		totalCount
		totalDuration
		items {
			day
			totalReviewCount
			workoutCount
			measurementCount
			audioBookCount
			animeCount
			bookCount
			podcastCount
			mangaCount
			showCount
			movieCount
			videoGameCount
			visualNovelCount
		}
	}
}

query FitnessAnalytics($input: DateRangeInput!) {
  fitnessAnalytics(input: $input) {
    workoutReps
    workoutWeight
    workoutDistance
    workoutRestTime
    workoutPersonalBests
    hours {
      hour
      count
    }
    workoutExercises {
      count
      exercise
    }
    workoutMuscles {
      count
      muscle
    }
    workoutEquipments {
      count
      equipment
    }
  }
}
