query CoreDetails {
	coreDetails {
		isPro
		version
		docsLink
		websiteUrl
		smtpEnabled
		oidcEnabled
		signupAllowed
		repositoryLink
		disableTelemetry
		tokenValidForDays
		localAuthDisabled
		fileStorageEnabled
		frontend {
			url
			pageSize
			oidcButtonLabel
			dashboardMessage
			umami {
				domains
				scriptUrl
				websiteId
			}
		}
	}
}
