query CreatorDetails($creatorId: Int!) {
  creatorDetails(creatorId: $creatorId) {
    details {
      id
      name
      displayImages
    }
    contents {
      name
      items {
        metadataId
        title
        image
      }
    }
  }
}
