query CreatorDetails($creatorId: Int!) {
  creatorDetails(creatorId: $creatorId) {
    details {
      id
      name
      image
    }
    contents {
      name
      items {
        lot
        details {
          identifier
          title
          image
          publishYear
        }
      }
    }
  }
}
