query CreatorsList($input: CreatorsListInput!) {
  creatorsList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      id
      name
      image
      mediaCount
    }
  }
}
