query ExerciseDetails($exerciseId: String!) {
  exerciseDetails(exerciseId: $exerciseId) {
    lot
    source
    level
    force
    mechanic
    equipment
    muscles
    attributes {
      instructions
      images
    }
  }
}
