query ExercisesList($input: ExercisesListInput!) {
  exercisesList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      id
      name
      lot
      attributes {
        images
        muscles
      }
    }
  }
}
