query ExerciseDetails($exerciseId: Int!) {
  exerciseDetails(exerciseId: $exerciseId) {
    name
    lot
    source
    level
    force
    mechanic
    equipment
    attributes {
      instructions
      images
      muscles
    }
  }
}
