query Exercises($page: Int!) {
  exercises(page: $page) {
    id
    name
    attributes {
      force
      level
      mechanic
      equipment
      primaryMuscles
      secondaryMuscles
      category
      instructions
      images
      alternateNames
    }
  }
}
