query Exercise($exerciseId: Int!) {
  exercise(exerciseId: $exerciseId) {
    name
    lot
    attributes {
      force
      level
      mechanic
      equipment
      primaryMuscles
      secondaryMuscles
      category
      instructions
      images
    }
  }
}
