query ExercisesList($input: ExercisesListInput!) {
  exercisesList(input: $input) {
    id
    name
    attributes {
      force
      level
      mechanic
      equipment
      primaryMuscles
      secondaryMuscles
      category
      instructions
      images
      alternateNames
    }
  }
}
