query GenreDetails($genreId: Int!) {
  genreDetails(genreId: $genreId) {
    details {
      id
      name
      numItems
    }
    contents {
      details {
        ...MediaSearchItemPart
      }
      metadataLot
    }
  }
}
