query ImportReports {
	importReports {
		id
		source
		progress
		startedOn
		finishedOn
		wasSuccess
		details {
			import {
				total
			}
			failedItems {
				lot
				step
				error
				identifier
			}
		}
	}
}
