query ImportReports {
	importReports {
		id
		source
		startedOn
		finishedOn
		wasSuccess
		details {
			import {
				total
			}
			failedItems {
				lot
				step
				identifier
				error
			}
		}
	}
}
