query LatestUserSummary {
  latestUserSummary {
    totalMetadataReviewCount
    totalCollectionReviewCount
    totalMetadataGroupReviewCount
    totalPersonReviewCount
    measurementCount
    workoutCount
    totalWorkoutDuration
    audioBookCount
    totalAudioBookDuration
    animeCount
    animeEpisodeCount
    bookCount
    totalBookPages
    podcastCount
    totalPodcastDuration
    mangaCount
    mangaChapterCount
    mangaVolumeCount
    movieCount
    totalMovieDuration
    showCount
    showSeasonCount
    showEpisodeCount
    totalShowDuration
    videoGameCount
    visualNovelCount
    totalVisualNovelDuration
    totalWorkoutPersonalBests
    totalWorkoutWeight
    totalWorkoutReps
    totalWorkoutDistance
    totalWorkoutRestTime
    totalMetadataCount
    totalReviewCount
    totalCount
    totalDuration
  }
}
