query LatestUserSummary {
	latestUserSummary {
		totalMetadataReviewCount
		totalCollectionReviewCount
		totalMetadataGroupReviewCount
		totalPersonReviewCount
		userMeasurementCount
		workoutCount
		totalWorkoutDuration
		audioBookCount
		totalAudioBookDuration
		animeCount
		bookCount
		totalBookPages
		podcastCount
		totalPodcastDuration
		mangaCount
		movieCount
		totalMovieDuration
		showCount
		totalShowDuration
		videoGameCount
		totalVideoGameDuration
		visualNovelCount
		totalVisualNovelDuration
		totalWorkoutPersonalBests
		totalWorkoutWeight
		totalWorkoutReps
		totalWorkoutDistance
		totalWorkoutRestTime
		totalMetadataCount
		totalReviewCount
		totalCount
		totalDuration
	}
}
