query MediaDetails($metadataId: Int!) {
  mediaDetails(metadataId: $metadataId) {
    title
    description
    type
    creators
    type
    posterImages
    backdropImages
    publishYear
    publishDate
		genres
    audioBookSpecifics {
      source
    }
    bookSpecifics {
      pages
      source
    }
    movieSpecifics {
      runtime
      source
    }
    podcastSpecifics {
      episodes {
        title
        overview
        thumbnail
        number
      }
      source
      totalEpisodes
    }
    showSpecifics {
      source
      seasons {
        seasonNumber
        name
        overview
        backdropImages
        posterImages
        episodes {
					id
          name
					posterImages
          episodeNumber
          publishDate
          name
          overview
        }
      }
    }
    videoGameSpecifics {
      source
    }
  }
}
