query MediaSearch($lot: MetadataLot!, $source: MetadataSource!, $input: SearchInput!) {
  mediaSearch(lot: $lot, source: $source, input: $input) {
    total
    nextPage
    items {
      databaseId
      item {
        identifier
        title
        images
        publishYear
      }
    }
  }
}
