query MediaDetails($metadataId: Identifier!) {
  mediaDetails(metadataId: $metadataId) {
    title
    description
    identifier
    lot
    source
    sourceUrl
    creators {
      name
      role
    }
    posterImages
    backdropImages
    publishYear
    publishDate
		genres
    animeSpecifics {
      episodes
    }
    bookSpecifics {
      pages
    }
    movieSpecifics {
      runtime
    }
    mangaSpecifics {
      volumes
      chapters
    }
    podcastSpecifics {
      episodes {
        title
        overview
        thumbnail
        number
        runtime
      }
      totalEpisodes
    }
    showSpecifics {
      seasons {
        seasonNumber
        name
        overview
        backdropImages
        posterImages
        episodes {
					id
          name
					posterImages
          episodeNumber
          publishDate
          name
          overview
          runtime
        }
      }
    }
    videoGameSpecifics {
      platforms
    }
  }
}
