query MediaSearch($input: MediaSearchInput!) {
  mediaSearch(input: $input) {
    details {
      total
      nextPage
    }
    items {
      databaseId
      hasInteracted
      item {
        identifier
        title
        image
        publishYear
      }
    }
  }
}
