query MediaItemReviews($metadataId: Identifier!) {
  mediaItemReviews(metadataId: $metadataId) {
    id
    rating
    text
    spoiler
    visibility
    seasonNumber
    episodeNumber
    postedOn
    postedBy {
      id
      name
    }
  }
}
