query MediaList($input: MediaListInput!) {
  mediaList(input: $input) {
    total
    nextPage
    items {
      averageRating
      data {
        identifier
        title
        images
        publishYear
      }
    }
  }
}
