query MediaItemReviews($metadataId: Int!) {
  mediaItemReviews(metadataId: $metadataId) {
    id
    rating
    text
    spoiler
    visibility
    showSeason
    showEpisode
    podcastEpisode
    postedOn
    postedBy {
      id
      name
    }
  }
}
