query MediaList($input: MediaListInput!) {
  mediaList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      averageRating
      data {
        identifier
        title
        image
        publishYear
      }
    }
  }
}
