query MetadataGroupDetails($metadataGroupId: Int!) {
  metadataGroupDetails(metadataGroupId: $metadataGroupId) {
    details {
      id
      title
      lot
      source
      displayImages
      parts
      isPartial
    }
    sourceUrl
    contents {
      ...PartialMetadataPart
    }
  }
}
