query MetadataSearch($input: MetadataSearchInput!) {
	metadataSearch(input: $input) {
		details {
			total
			nextPage
		}
		items {
			databaseId
			hasInteracted
			item {
				identifier
				title
				image
				publishYear
			}
		}
	}
}
