query MetadataGroupDetails($metadataGroupId: String!) {
	metadataGroupDetails(metadataGroupId: $metadataGroupId) {
		contents
		sourceUrl
		details {
			id
			title
			lot
			source
			displayImages
			identifier
			parts
			isPartial
		}
	}
}
