query MetadataGroupsList($input: SearchInput!) {
  metadataGroupsList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      id
      title
      lot
      parts
      image
    }
  }
}
