query PersonDetails($personId: String!) {
  personDetails(personId: $personId) {
    sourceUrl
    details {
      id
      name
      source
      isPartial
      description
      birthDate
      deathDate
      place
      website
      gender
      displayImages
    }
    contents {
      name
      items {
        mediaId
        character
      }
    }
  }
}
