query PersonDetails($personId: String!) {
	personDetails(personId: $personId) {
		details {
			id
			name
			source
			identifier
			isPartial
			description
			birthDate
			deathDate
			place
			website
			gender
			displayImages
			sourceUrl
		}
		contents {
			name
			count
			items {
				character
				metadataId
			}
		}
	}
}
