query PersonDetails($personId: String!) {
	personDetails(personId: $personId) {
		associatedMetadata {
			name
			count
			items {
				entityId
				character
			}
		}
		details {
			id
			name
			place
			source
			gender
			website
			deathDate
			birthDate
			isPartial
			sourceUrl
			identifier
			description
			displayImages
		}
	}
}
