query SeenHistory($metadataId: Identifier!) {
  seenHistory(metadataId: $metadataId) {
    id
    progress
		dropped
    startedOn
    finishedOn
    lastUpdatedOn
		showInformation {
			episode
			season
		}
		podcastInformation {
			episode
		}
  }
}
