query UserExerciseDetails($exerciseId: Int!) {
  userExerciseDetails(exerciseId: $exerciseId) {
    history {
      workoutId
      workoutName
      workoutTime
      sets {
        lot
        statistic {
          ...WorkoutSetStatisticPart
        }
      }
    }
    details {
      exerciseId
      numTimesPerformed
      lastUpdatedOn
      extraInformation {
        lifetimeStats {
          weight
          reps
          distance
          duration
        }
        personalBests {
          lot
          sets {
            workoutId
            setIdx
            data {
              statistic {
                ...WorkoutSetStatisticPart
              }
              lot
              personalBests
            }
          }
        }
      }
    }
  }
}
