fragment SeenPart on Seen {
  id
  progress
  state
  startedOn
  finishedOn
  lastUpdatedOn
  showInformation {
    episode
    season
  }
  podcastInformation {
    episode
  }
}

query UserMediaDetails($metadataId: Int!) {
  userMediaDetails(metadataId: $metadataId) {
    collections {
      id
      name
    }
    inProgress {
      ...SeenPart
    }
    history {
      ...SeenPart
    }
    reviews {
      id
      rating
      text
      spoiler
      visibility
      showSeason
      showEpisode
      podcastEpisode
      postedOn
      postedBy {
        id
        name
      }
    }
    reminder {
      remindOn
      message
    }
    isMonitored
    seenBy
    nextEpisode {
      seasonNumber
      episodeNumber
    }
  }
}
