query UserDetails {
	userDetails {
		__typename
		... on UserDetails {
			id
			lot
			name
			isDisabled
			oidcIssuerId
			isTwoFactorEnabled
			extraInformation {
				scheduledForWorkoutRevision
			}
			preferences {
				general {
					reviewScale
					gridPacking
					displayNsfw
					landingPath
					listPageSize
					disableVideos
					persistQueries
					disableReviews
					disableIntegrations
					disableWatchProviders
					showSpoilersInCalendar
					disableNavigationAnimation
					dashboard {
						hidden
						section
						numElements
						deduplicateMedia
					}
					watchProviders {
						lot
						values
					}
				}
				fitness {
					exercises {
						unitSystem
						setRestTimers {
							...SetRestTimersPart
						}
					}
					logging {
						muteSounds
						caloriesBurntUnit
						promptForRestTimer
						startTimerForDurationExercises
					}
					measurements {
						statistics {
							name
							unit
						}
					}
				}
				featuresEnabled {
					analytics {
						enabled
					}
					others {
						calendar
						collections
					}
					fitness {
						enabled
						workouts
						templates
						measurements
					}
					media {
						enabled
						groups
						people
						genres
						specific
					}
				}
			}
		}
	}
}
