query UserCreatorDetails($creatorId: Int!) {
  userCreatorDetails(creatorId: $creatorId) {
    reviews {
      id
      rating
      text
      spoiler
      visibility
      postedOn
      postedBy {
        id
        name
      }
      comments {
        id
        text
        createdOn
        user {
          id
          name
        }
        likedBy
      }
    }
  }
}
