query UserPreferences {
  userPreferences {
    general {
      reviewScale
    }
    fitness {
      measurements {
        custom {
          name
          dataType
        }
        inbuilt {
          weight
          bodyMassIndex
          totalBodyWater
          muscle
          leanBodyMass
          bodyFat
          boneMass
          visceralFat
          waistCircumference
          waistToHeightRatio
          hipCircumference
          waistToHipRatio
          chestCircumference
          thighCircumference
          bicepsCircumference
          neckCircumference
          bodyFatCaliper
          chestSkinfold
          abdominalSkinfold
          thighSkinfold
          basalMetabolicRate
          totalDailyEnergyExpenditure
          calories
        }
      }
      exercises {
        saveHistory
        unitSystem
      }
    }
    notifications {
      episodeReleased
      episodeNameChanged
      statusChanged
      releaseDateChanged
      numberOfSeasonsChanged
    }
    featuresEnabled {
      fitness {
        enabled
        measurements
      }
      media {
        enabled
        anime
        audioBook
        book
        manga
        movie
        podcast
        show
        videoGame
        visualNovel
      }
    }
  }
}
