query UserPreferences {
  userPreferences {
    fitness {
      measurements {
        custom
        inbuiltDisabled
      }
      exercises {
        saveHistory
      }
    }
    notifications {
      episodeReleased
      statusChanged
      releaseDateChanged
      numberOfSeasonsChanged
    }
    featuresEnabled {
      media {
        anime
        audioBooks
        books
        manga
        movies
        podcasts
        shows
        videoGames
      }
    }
  }
}
