query UserMeasurementsList($input: UserMeasurementsListInput!) {
	userMeasurementsList(input: $input) {
		timestamp
		name
		comment
		information {
			assets {
				...EntityAssetsPart
			}
			statistics {
				name
				value
			}
		}
	}
}
