query UserWorkoutTemplatesList($input: SearchInput!) {
	userWorkoutTemplatesList(input: $input) {
		details {
			total
			nextPage
		}
		items {
			id
			name
			createdOn
			visibility
			summary {
				...WorkoutSummaryPart
			}
		}
	}
}
