query UserMediaDetails($metadataId: Int!) {
  userMediaDetails(metadataId: $metadataId) {
    collections {
      id
      name
    }
    inProgress {
      ...SeenPart
    }
    history {
      ...SeenPart
    }
    averageRating
    reviews {
      ...ReviewItemPart
    }
    reminder {
      remindOn
      message
    }
    isMonitored
    seenBy
    nextEpisode {
      seasonNumber
      episodeNumber
    }
  }
}
