fragment CalendarEventPart on GraphqlCalendarEvent {
    calendarEventId
    metadataId
    metadataTitle
    metadataLot
    showSeasonNumber
    showEpisodeNumber
    podcastEpisodeNumber
}

query UserCalendarEvents($input: UserCalendarEventInput!) {
  userCalendarEvents(input: $input) {
    date
    events {
      ...CalendarEventPart
    }
  }
}
