query UserMetadataGroupDetails($metadataGroupId: String!) {
	userMetadataGroupDetails(metadataGroupId: $metadataGroupId) {
		reviews {
			...ReviewItemPart
		}
		collections {
			...CollectionPart
		}
	}
}
