query UserMetadataGroupDetails($metadataGroupId: Int!) {
  userMetadataGroupDetails(metadataGroupId: $metadataGroupId) {
    reviews {
      ...ReviewItemPart
    }
    collections {
      ...CollectionPart
    }
    ownership {
      ...UserMediaOwnershipPart
    }
    reminder {
      ...UserMediaReminderPart
    }
  }
}
