query UserMetadataDetails($metadataId: String!) {
  userMetadataDetails(metadataId: $metadataId) {
    collections {
      ...CollectionPart
    }
    inProgress {
      ...SeenPart
    }
    history {
      ...SeenPart
    }
    averageRating
    unitsConsumed
    reviews {
      ...ReviewItemPart
    }
    seenByAllCount
    seenByUserCount
    nextEntry {
      season
      episode
      chapter
    }
    showProgress {
      timesSeen
      seasonNumber
      episodes {
        episodeNumber
        timesSeen
      }
    }
    podcastProgress {
      episodeNumber
      timesSeen
    }
  }
}
