query UserCalendarEvents($startTime: NaiveDate, $endTime: NaiveDate) {
  userCalendarEvents(startTime: $startTime, endTime: $endTime) {
    calendarEventId
    metadataId
    metadataTitle
    metadataLot
    showSeasonNumber
    showEpisodeNumber
    podcastEpisodeNumber
  }
}
