query UserPersonDetails($personId: Int!) {
  userPersonDetails(personId: $personId) {
    isMonitored
    collections {
      ...CollectionPart
    }
    reviews {
      ...ReviewItemPart
    }
    reminder {
      ...UserMediaReminderPart
    }
  }
}
