query UserEnabledFeatures {
  userEnabledFeatures {
    general {
      fileStorage {
        enabled
      }
    }
    metadata {
      anime
      audioBooks
      books
      manga
      movies
      podcasts
      shows
      videoGames
    }
  }
}
