query UserSummary {
  userSummary {
    books {
      pages
      read
    }
    movies {
      runtime
      watched
    }
    podcasts {
      runtime
      played
      playedEpisodes
    }
    videoGames {
      played
    }
    shows {
      runtime
      watchedEpisodes
      watchedSeasons
			watched
    }
    audioBooks {
      runtime
      played
    }
  }
}
