query UserWorkoutsList($input: SearchInput!) {
	userWorkoutsList(input: $input) {
		details {
			total
			nextPage
		}
		items {
			id
			name
			endTime
			duration
			startTime
			summary {
				...WorkoutSummaryPart
			}
		}
	}
}
