query UserWorkoutDetails($workoutId: String!) {
	userWorkoutDetails(workoutId: $workoutId) {
		collections {
			...CollectionPart
		}
		details {
			id
			name
			endTime
			duration
			startTime
			templateId
			repeatedFrom
			summary {
				...WorkoutSummaryPart
			}
			information {
				...WorkoutInformationPart
			}
		}
	}
}
