query UserPreferences {
  userPreferences {
    general {
      reviewScale
      gridPacking
      displayNsfw
      disableVideos
      persistQueries
      disableReviews
      disableIntegrations
      disableWatchProviders
      disableNavigationAnimation
      dashboard {
        section
        hidden
        numElements
      }
      watchProviders {
        lot
        values
      }
    }
    fitness {
      measurements {
        custom {
          name
          dataType
        }
        inbuilt {
          weight
          bodyMassIndex
          totalBodyWater
          muscle
          leanBodyMass
          bodyFat
          boneMass
          visceralFat
          waistCircumference
          waistToHeightRatio
          hipCircumference
          waistToHipRatio
          chestCircumference
          thighCircumference
          bicepsCircumference
          neckCircumference
          bodyFatCaliper
          chestSkinfold
          abdominalSkinfold
          thighSkinfold
          basalMetabolicRate
          totalDailyEnergyExpenditure
          calories
        }
      }
      exercises {
        unitSystem
      }
    }
    notifications {
      toSend
      enabled
    }
    featuresEnabled {
      others {
        calendar
        collections
      }
      fitness {
        enabled
        workouts
        templates
        measurements
      }
      media {
        enabled
        anime
        audioBook
        book
        manga
        movie
        podcast
        show
        videoGame
        visualNovel
        people
        groups
        genres
      }
    }
  }
}
