query UserMetadataDetails($metadataId: String!) {
	userMetadataDetails(metadataId: $metadataId) {
		mediaReason
		hasInteracted
		collections {
			...CollectionPart
		}
		inProgress {
			...SeenPart
		}
		history {
			...SeenPart
		}
		averageRating
		reviews {
			...ReviewItemPart
		}
		seenByAllCount
		seenByUserCount
		nextEntry {
			season
			volume
			episode
			chapter
		}
		showProgress {
			timesSeen
			seasonNumber
			episodes {
				episodeNumber
				timesSeen
			}
		}
		podcastProgress {
			episodeNumber
			timesSeen
		}
	}
}
