query UserWorkoutList($input: SearchInput!) {
  userWorkoutList(input: $input) {
    details {
      total
      nextPage
    }
    items {
      id
      name
      startTime
      endTime
      summary {
        ...WorkoutSummaryPart
      }
    }
  }
}
