query WorkoutDetails($workoutId: String!) {
  workoutDetails(workoutId: $workoutId) {
    name
    comment
    startTime
    endTime
    summary {
      ...WorkoutSummaryPart
    }
    information {
      assets {
        ...EntityAssetsPart
      }
      exercises {
        id
        name
        lot
        notes
        restTime
        total {
          ...WorkoutTotalMeasurementPart
        }
        assets {
          ...EntityAssetsPart
        }
        sets {
          statistic {
            ...WorkoutSetStatisticPart
          }
          lot
          personalBests
        }
      }
    }
  }
}
