query WorkoutDetails($workoutId: String!) {
  workoutDetails(workoutId: $workoutId) {
    collections {
      ...CollectionPart
    }
    details {
      id
      name
      endTime
      duration
      startTime
      repeatedFrom
      summary {
        ...WorkoutSummaryPart
      }
      information {
        ...WorkoutInformationPart
      }
    }
  }
}
