query WorkoutDetails($workoutId: String!) {
  workoutDetails(workoutId: $workoutId) {
    id
    name
    endTime
    startTime
    repeatedFrom
    summary {
      ...WorkoutSummaryPart
    }
    information {
      ...WorkoutInformationPart
    }
  }
}
