query WorkoutTemplateDetails($workoutTemplateId: String!) {
  workoutTemplateDetails(workoutTemplateId: $workoutTemplateId) {
    collections {
      ...CollectionPart
    }
    details {
      id
      name
      createdOn
      visibility
      summary {
        ...WorkoutSummaryPart
      }
      information {
        ...WorkoutInformationPart
      }
    }
  }
}
