use std::sync::Arc;

use async_graphql::{Context, Object, Result};
use common_models::StringIdObject;
use database_models::access_link;
use dependent_models::{BasicUserDetails, UserDetailsResult};
use media_models::{
    CreateAccessLinkInput, GetPasswordChangeSessionInput, GetPasswordChangeSessionResponse,
    ProcessAccessLinkInput, ProcessAccessLinkResult, SetPasswordViaSessionInput, UserResetResult,
};
use traits::AuthProvider;
use user_models::{UpdateUserInput, UserPreferences};
use user_service::UserService;

#[derive(Default)]
pub struct ManagementQuery;

impl AuthProvider for ManagementQuery {}

#[Object]
impl ManagementQuery {
    /// Get details about all the users in the service.
    async fn users_list(
        &self,
        gql_ctx: &Context<'_>,
        query: Option<String>,
    ) -> Result<Vec<BasicUserDetails>> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let response = service.users_list(query).await?;
        Ok(response)
    }

    /// Get details about the currently logged in user.
    async fn user_details(&self, gql_ctx: &Context<'_>) -> Result<UserDetailsResult> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let session_id = self.user_session_id_from_ctx(gql_ctx)?;
        let response = service.user_details(&session_id).await?;
        Ok(response)
    }

    /// Get all access links generated by the currently logged in user.
    async fn user_access_links(&self, gql_ctx: &Context<'_>) -> Result<Vec<access_link::Model>> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let user_id = self.user_id_from_ctx(gql_ctx).await?;
        let response = service.user_access_links(&user_id).await?;
        Ok(response)
    }
}

#[derive(Default)]
pub struct ManagementMutation;

impl AuthProvider for ManagementMutation {
    fn is_mutation(&self) -> bool {
        true
    }
}

#[Object]
impl ManagementMutation {
    /// Delete a user. The account deleting the user must be an `Admin`.
    async fn delete_user(&self, gql_ctx: &Context<'_>, to_delete_user_id: String) -> Result<bool> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let user_id = self.user_id_from_ctx(gql_ctx).await?;
        let response = service.delete_user(user_id, to_delete_user_id).await?;
        Ok(response)
    }

    /// Reset a user by deleting and recreating them with the same ID. The account
    /// resetting the user must be an `Admin`.
    async fn reset_user(
        &self,
        gql_ctx: &Context<'_>,
        to_reset_user_id: String,
    ) -> Result<UserResetResult> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let user_id = self.user_id_from_ctx(gql_ctx).await?;
        let response = service.reset_user(user_id, to_reset_user_id).await?;
        Ok(response)
    }

    /// Update a user's profile details.
    async fn update_user(
        &self,
        gql_ctx: &Context<'_>,
        input: UpdateUserInput,
    ) -> Result<StringIdObject> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let requester_user_id = self.user_id_from_ctx(gql_ctx).await.ok();
        let response = service.update_user(requester_user_id, input).await?;
        Ok(response)
    }

    /// Change a user's preferences.
    async fn update_user_preference(
        &self,
        gql_ctx: &Context<'_>,
        input: UserPreferences,
    ) -> Result<bool> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let user_id = self.user_id_from_ctx(gql_ctx).await?;
        let response = service.update_user_preference(user_id, input).await?;
        Ok(response)
    }

    /// Get a URL which can be used to set a new password for the user.
    async fn get_password_change_session(
        &self,
        gql_ctx: &Context<'_>,
        input: GetPasswordChangeSessionInput,
    ) -> Result<GetPasswordChangeSessionResponse> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let requester_user_id = self.user_id_from_ctx(gql_ctx).await.ok();
        let response = service
            .get_password_change_session(requester_user_id, input)
            .await?;
        Ok(response)
    }

    /// Set password using a valid session ID (non-authenticated route).
    async fn set_password_via_session(
        &self,
        gql_ctx: &Context<'_>,
        input: SetPasswordViaSessionInput,
    ) -> Result<bool> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let response = service.set_password_via_session(input).await?;
        Ok(response)
    }

    /// Create or edit an access link.
    async fn create_access_link(
        &self,
        gql_ctx: &Context<'_>,
        input: CreateAccessLinkInput,
    ) -> Result<StringIdObject> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let user_id = self.user_id_from_ctx(gql_ctx).await?;
        let response = service.create_access_link(input, user_id).await?;
        Ok(response)
    }

    /// Get an access token using an access link.
    async fn process_access_link(
        &self,
        gql_ctx: &Context<'_>,
        input: ProcessAccessLinkInput,
    ) -> Result<ProcessAccessLinkResult> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        let response = service.process_access_link(input).await?;
        Ok(response)
    }

    /// Revoke an access link.
    async fn revoke_access_link(
        &self,
        gql_ctx: &Context<'_>,
        access_link_id: String,
    ) -> Result<bool> {
        let service = gql_ctx.data_unchecked::<Arc<UserService>>();
        self.user_id_from_ctx(gql_ctx).await?;
        let response = service.revoke_access_link(access_link_id).await?;
        Ok(response)
    }
}
