import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";
import { getAppBackendOpenApiDocument } from "../app/api";

const generatedFileHeader = `/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

`;

export const generateOpenApiTypes = async (
	outputPath: string,
	origin: string,
) => {
	const document = JSON.parse(
		JSON.stringify(getAppBackendOpenApiDocument(origin)),
	);
	const ast = await openapiTS(document);
	const contents = generatedFileHeader + astToString(ast);

	mkdirSync(dirname(outputPath), { recursive: true });
	writeFileSync(outputPath, contents, "utf8");
};
