import type { ImageSourcePropType } from "react-native";

import { getAndroidNativeTabIconPath, type AndroidMaterialSymbolPath } from "./native-tab-icons";

const materialSymbols: Record<AndroidMaterialSymbolPath, ImageSourcePropType> = {
	"@expo/material-symbols/tv.xml": require("@expo/material-symbols/tv.xml"),
	"@expo/material-symbols/mic.xml": require("@expo/material-symbols/mic.xml"),
	"@expo/material-symbols/add.xml": require("@expo/material-symbols/add.xml"),
	"@expo/material-symbols/bolt.xml": require("@expo/material-symbols/bolt.xml"),
	"@expo/material-symbols/home.xml": require("@expo/material-symbols/home.xml"),
	"@expo/material-symbols/book.xml": require("@expo/material-symbols/book.xml"),
	"@expo/material-symbols/menu.xml": require("@expo/material-symbols/menu.xml"),
	"@expo/material-symbols/sell.xml": require("@expo/material-symbols/sell.xml"),
	"@expo/material-symbols/star.xml": require("@expo/material-symbols/star.xml"),
	"@expo/material-symbols/check.xml": require("@expo/material-symbols/check.xml"),
	"@expo/material-symbols/inbox.xml": require("@expo/material-symbols/inbox.xml"),
	"@expo/material-symbols/album.xml": require("@expo/material-symbols/album.xml"),
	"@expo/material-symbols/group.xml": require("@expo/material-symbols/group.xml"),
	"@expo/material-symbols/movie.xml": require("@expo/material-symbols/movie.xml"),
	"@expo/material-symbols/close.xml": require("@expo/material-symbols/close.xml"),
	"@expo/material-symbols/radio.xml": require("@expo/material-symbols/radio.xml"),
	"@expo/material-symbols/search.xml": require("@expo/material-symbols/search.xml"),
	"@expo/material-symbols/folder.xml": require("@expo/material-symbols/folder.xml"),
	"@expo/material-symbols/circle.xml": require("@expo/material-symbols/circle.xml"),
	"@expo/material-symbols/layers.xml": require("@expo/material-symbols/layers.xml"),
	"@expo/material-symbols/refresh.xml": require("@expo/material-symbols/refresh.xml"),
	"@expo/material-symbols/bookmark.xml": require("@expo/material-symbols/bookmark.xml"),
	"@expo/material-symbols/favorite.xml": require("@expo/material-symbols/favorite.xml"),
	"@expo/material-symbols/podcasts.xml": require("@expo/material-symbols/podcasts.xml"),
	"@expo/material-symbols/apartment.xml": require("@expo/material-symbols/apartment.xml"),
	"@expo/material-symbols/bookmarks.xml": require("@expo/material-symbols/bookmarks.xml"),
	"@expo/material-symbols/checklist.xml": require("@expo/material-symbols/checklist.xml"),
	"@expo/material-symbols/dark_mode.xml": require("@expo/material-symbols/dark_mode.xml"),
	"@expo/material-symbols/swap_vert.xml": require("@expo/material-symbols/swap_vert.xml"),
	"@expo/material-symbols/menu_book.xml": require("@expo/material-symbols/menu_book.xml"),
	"@expo/material-symbols/straighten.xml": require("@expo/material-symbols/straighten.xml"),
	"@expo/material-symbols/star_shine.xml": require("@expo/material-symbols/star_shine.xml"),
	"@expo/material-symbols/more_horiz.xml": require("@expo/material-symbols/more_horiz.xml"),
	"@expo/material-symbols/headphones.xml": require("@expo/material-symbols/headphones.xml"),
	"@expo/material-symbols/cardiology.xml": require("@expo/material-symbols/cardiology.xml"),
	"@expo/material-symbols/light_mode.xml": require("@expo/material-symbols/light_mode.xml"),
	"@expo/material-symbols/music_note.xml": require("@expo/material-symbols/music_note.xml"),
	"@expo/material-symbols/view_kanban.xml": require("@expo/material-symbols/view_kanban.xml"),
	"@expo/material-symbols/play_circle.xml": require("@expo/material-symbols/play_circle.xml"),
	"@expo/material-symbols/content_copy.xml": require("@expo/material-symbols/content_copy.xml"),
	"@expo/material-symbols/video_library.xml": require("@expo/material-symbols/video_library.xml"),
	"@expo/material-symbols/chevron_right.xml": require("@expo/material-symbols/chevron_right.xml"),
	"@expo/material-symbols/local_library.xml": require("@expo/material-symbols/local_library.xml"),
	"@expo/material-symbols/photo_library.xml": require("@expo/material-symbols/photo_library.xml"),
	"@expo/material-symbols/smart_display.xml": require("@expo/material-symbols/smart_display.xml"),
	"@expo/material-symbols/sports_esports.xml": require("@expo/material-symbols/sports_esports.xml"),
	"@expo/material-symbols/account_circle.xml": require("@expo/material-symbols/account_circle.xml"),
	"@expo/material-symbols/fitness_center.xml": require("@expo/material-symbols/fitness_center.xml"),
	"@expo/material-symbols/drag_indicator.xml": require("@expo/material-symbols/drag_indicator.xml"),
	"@expo/material-symbols/desktop_windows.xml": require("@expo/material-symbols/desktop_windows.xml"),
	"@expo/material-symbols/side_navigation.xml": require("@expo/material-symbols/side_navigation.xml"),
	"@expo/material-symbols/keyboard_arrow_down.xml": require("@expo/material-symbols/keyboard_arrow_down.xml"),
};

export function getAndroidNativeTabIcon(name: string) {
	return materialSymbols[getAndroidNativeTabIconPath(name)];
}
