//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

use async_graphql::{InputObject, SimpleObject};
use async_trait::async_trait;
use database::{IntegrationLot, IntegrationSource};
use nanoid::nanoid;
use sea_orm::{entity::prelude::*, ActiveValue};

use crate::models::media::IntegrationSourceSpecifics;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, SimpleObject, InputObject)]
#[sea_orm(table_name = "integration")]
#[graphql(name = "Integration", input_name = "IntegrationInput")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    #[graphql(skip_input)]
    pub id: String,
    #[graphql(skip)]
    pub user_id: String,
    pub lot: IntegrationLot,
    pub source: IntegrationSource,
    #[graphql(skip_input)]
    pub created_on: DateTimeWithTimeZone,
    #[graphql(skip_input)]
    pub last_triggered_on: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Json")]
    pub source_specifics: Option<IntegrationSourceSpecifics>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

#[async_trait]
impl ActiveModelBehavior for ActiveModel {
    async fn before_save<C>(mut self, _db: &C, insert: bool) -> Result<Self, DbErr>
    where
        C: ConnectionTrait,
    {
        if insert {
            self.id = ActiveValue::Set(format!("int_{}", nanoid!(12)));
        }
        Ok(self)
    }
}
