//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::migrator::MetadataToPartialMetadataRelation;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "metadata_to_partial_metadata")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub metadata_id: i32,
    pub relation: MetadataToPartialMetadataRelation,
    #[sea_orm(primary_key, auto_increment = false)]
    pub partial_metadata_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::metadata::Entity",
        from = "Column::MetadataId",
        to = "super::metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Metadata,
    #[sea_orm(
        belongs_to = "super::partial_metadata::Entity",
        from = "Column::PartialMetadataId",
        to = "super::partial_metadata::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    PartialMetadata,
}

impl Related<super::metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Metadata.def()
    }
}

impl Related<super::partial_metadata::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PartialMetadata.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
