//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

pub mod prelude;

pub mod book;
pub mod creator;
pub mod episode;
pub mod metadata;
pub mod metadata_image;
pub mod metadata_to_creator;
pub mod movie;
pub mod season;
pub mod seen;
pub mod show;
pub mod token;
pub mod user;
pub mod user_to_metadata;
