//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.2

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, Default)]
#[sea_orm(table_name = "summary")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub user_id: i32,
    pub created_on: DateTimeUtc,
    pub books_pages: i32,
    pub books_read: i32,
    pub movies_runtime: i32,
    pub movies_watched: i32,
    pub shows_runtime: i32,
    pub shows_watched: i32,
    pub shows_episodes_watched: i32,
    pub shows_seasons_watched: i32,
    pub video_games_played: i32,
    pub audio_books_runtime: i32,
    pub audio_books_played: i32,
    pub podcasts_runtime: i32,
    pub podcasts_played: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
