//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.1

use async_graphql::{InputObject, SimpleObject};
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

use crate::models::fitness::UserMeasurementStats;

#[derive(
    Clone,
    Debug,
    PartialEq,
    DeriveEntityModel,
    Eq,
    Serialize,
    Deserialize,
    SimpleObject,
    InputObject,
)]
#[graphql(name = "UserMeasurement", input_name = "UserMeasurementInput")]
#[sea_orm(table_name = "user_measurement")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub timestamp: DateTime,
    #[graphql(skip)]
    #[sea_orm(primary_key, auto_increment = false)]
    pub user_id: i32,
    pub name: Option<String>,
    pub comment: Option<String>,
    pub stats: UserMeasurementStats,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::user::Entity",
        from = "Column::UserId",
        to = "super::user::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    User,
}

impl Related<super::user::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::User.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
