import type { LotEntityMigrationTarget } from "./shared";

export const metadataMigrationTargets = [
	{
		lot: "audio_book",
		source: "audible",
		entitySchemaSlug: "audiobook",
		providerSlug: "audiobook.audible",
	},
	{ source: "custom", lot: "audio_book", providerSlug: null, entitySchemaSlug: "audiobook" },
	{ lot: "anime", source: "anilist", entitySchemaSlug: "anime", providerSlug: "anime.anilist" },
	{ lot: "anime", source: "custom", providerSlug: null, entitySchemaSlug: "anime" },
	{
		lot: "anime",
		source: "myanimelist",
		entitySchemaSlug: "anime",
		providerSlug: "anime.myanimelist",
	},
	{ lot: "book", source: "custom", providerSlug: null, entitySchemaSlug: "book" },
	{
		lot: "book",
		source: "google_books",
		entitySchemaSlug: "book",
		providerSlug: "book.google-books",
	},
	{ lot: "book", source: "hardcover", entitySchemaSlug: "book", providerSlug: "book.hardcover" },
	{
		lot: "book",
		source: "openlibrary",
		entitySchemaSlug: "book",
		providerSlug: "book.openlibrary",
	},
	{ source: "custom", lot: "comic_book", providerSlug: null, entitySchemaSlug: "comic-book" },
	{
		source: "metron",
		lot: "comic_book",
		entitySchemaSlug: "comic-book",
		providerSlug: "comic-book.metron",
	},
	{ lot: "manga", source: "anilist", entitySchemaSlug: "manga", providerSlug: "manga.anilist" },
	{ lot: "manga", source: "custom", providerSlug: null, entitySchemaSlug: "manga" },
	{
		lot: "manga",
		source: "manga_updates",
		entitySchemaSlug: "manga",
		providerSlug: "manga.manga-updates",
	},
	{
		lot: "manga",
		source: "myanimelist",
		entitySchemaSlug: "manga",
		providerSlug: "manga.myanimelist",
	},
	{ lot: "movie", source: "custom", providerSlug: null, entitySchemaSlug: "movie" },
	{ lot: "movie", source: "tmdb", entitySchemaSlug: "movie", providerSlug: "movie.tmdb" },
	{ lot: "movie", source: "tvdb", entitySchemaSlug: "movie", providerSlug: "movie.tvdb" },
	{ lot: "music", source: "custom", providerSlug: null, entitySchemaSlug: "music" },
	{
		lot: "music",
		source: "music_brainz",
		entitySchemaSlug: "music",
		providerSlug: "music.music-brainz",
	},
	{ lot: "music", source: "spotify", entitySchemaSlug: "music", providerSlug: "music.spotify" },
	{
		lot: "music",
		source: "youtube_music",
		entitySchemaSlug: "music",
		providerSlug: "music.youtube-music",
	},
	{ lot: "podcast", source: "custom", providerSlug: null, entitySchemaSlug: "podcast" },
	{ lot: "podcast", source: "itunes", entitySchemaSlug: "podcast", providerSlug: "podcast.itunes" },
	{
		lot: "podcast",
		source: "listennotes",
		entitySchemaSlug: "podcast",
		providerSlug: "podcast.listennotes",
	},
	{ lot: "show", source: "custom", providerSlug: null, entitySchemaSlug: "show" },
	{ lot: "show", source: "tmdb", entitySchemaSlug: "show", providerSlug: "show.tmdb" },
	{ lot: "show", source: "tvdb", entitySchemaSlug: "show", providerSlug: "show.tvdb" },
	{ source: "custom", lot: "video_game", providerSlug: null, entitySchemaSlug: "video-game" },
	{
		lot: "video_game",
		source: "giant_bomb",
		entitySchemaSlug: "video-game",
		providerSlug: "video-game.giant-bomb",
	},
	{
		source: "igdb",
		lot: "video_game",
		entitySchemaSlug: "video-game",
		providerSlug: "video-game.igdb",
	},
	{ source: "custom", providerSlug: null, lot: "visual_novel", entitySchemaSlug: "visual-novel" },
	{
		source: "vndb",
		lot: "visual_novel",
		entitySchemaSlug: "visual-novel",
		providerSlug: "visual-novel.vndb",
	},
] as const satisfies readonly LotEntityMigrationTarget[];
