/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check backend health */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Database and Redis checks passed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @enum {string} */
                                status: "healthy";
                            };
                        };
                    };
                };
                /** @description Database or Redis checks failed */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["HealthCheckFailedError"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export metrics in Prometheus format */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Prometheus metrics in text format */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authentication/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current user session */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Authenticated session details */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                user?: unknown;
                                session?: unknown;
                            };
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/authentication/email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a user account */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        /** Format: email */
                        email: string;
                        password: string;
                    };
                };
            };
            responses: {
                /** @description User account was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** @enum {boolean} */
                                created: true;
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sandbox/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run a sandbox script */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        code: string;
                    };
                };
            };
            responses: {
                /** @description Sandbox run completed */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                logs?: string | null;
                                error?: string | null;
                                value?: unknown;
                                durationMs: number;
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facets/list": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List facets available for the user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Facets available for the user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                config?: unknown;
                                enabled: boolean;
                                isBuiltin: boolean;
                                icon: string;
                                description?: string | null;
                                accentColor: string;
                                sortOrder: number;
                            }[];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facets/create": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create and enable a custom facet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        slug?: string;
                        icon: string;
                        accentColor: string;
                        description?: string;
                    };
                };
            };
            responses: {
                /** @description Facet was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                config?: unknown;
                                enabled: boolean;
                                isBuiltin: boolean;
                                icon: string;
                                description?: string | null;
                                accentColor: string;
                                sortOrder: number;
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/facets/{facetId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a facet */
        patch: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    facetId: string;
                };
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        enabled?: boolean;
                        description?: string | unknown;
                        accentColor?: string;
                        icon?: string;
                        name?: string;
                        slug?: string;
                    };
                };
            };
            responses: {
                /** @description Facet was updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                slug: string;
                                name: string;
                                config?: unknown;
                                enabled: boolean;
                                isBuiltin: boolean;
                                icon: string;
                                description?: string | null;
                                accentColor: string;
                                sortOrder: number;
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Facet does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        trace?: never;
    };
    "/facets/reorder": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reorder facets for the user */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        facetIds: string[];
                    };
                };
            };
            responses: {
                /** @description Facet order was updated */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                facetIds: string[];
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entity-schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entity schemas for a custom facet */
        get: {
            parameters: {
                query: {
                    facetId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entity schemas for the requested facet */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                slug: string;
                                facetId: string;
                                isBuiltin: boolean;
                                icon: string;
                                accentColor: string;
                                propertiesSchema: {
                                    [key: string]: components["schemas"]["AppPropertyDefinition"];
                                };
                            }[];
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Facet does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an entity schema for a custom facet */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        slug?: string;
                        icon: string;
                        facetId: string;
                        accentColor: string;
                        propertiesSchema: {
                            [key: string]: components["schemas"]["AppPropertyDefinition"];
                        };
                    };
                };
            };
            responses: {
                /** @description Entity schema was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                slug: string;
                                facetId: string;
                                isBuiltin: boolean;
                                icon: string;
                                accentColor: string;
                                propertiesSchema: {
                                    [key: string]: components["schemas"]["AppPropertyDefinition"];
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Facet does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List entities for a custom entity schema */
        get: {
            parameters: {
                query: {
                    entitySchemaId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Entities for the requested entity schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                entitySchemaId: string;
                                externalId: string | null;
                                image: {
                                    /** Format: uri */
                                    url: string;
                                    /** @enum {string} */
                                    kind: "remote";
                                } | {
                                    /** @enum {string} */
                                    kind: "s3";
                                    key: string;
                                } | unknown;
                                detailsSandboxScriptId: string | null;
                                properties: {
                                    [key: string]: unknown;
                                };
                            }[];
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity schema does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an entity for a custom entity schema */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        image: {
                            /** Format: uri */
                            url: string;
                            /** @enum {string} */
                            kind: "remote";
                        } | {
                            /** @enum {string} */
                            kind: "s3";
                            key: string;
                        } | unknown;
                        entitySchemaId: string;
                        properties: {
                            [key: string]: unknown;
                        };
                    };
                };
            };
            responses: {
                /** @description Entity was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                entitySchemaId: string;
                                externalId: string | null;
                                image: {
                                    /** Format: uri */
                                    url: string;
                                    /** @enum {string} */
                                    kind: "remote";
                                } | {
                                    /** @enum {string} */
                                    kind: "s3";
                                    key: string;
                                } | unknown;
                                detailsSandboxScriptId: string | null;
                                properties: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity schema does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/entities/{entityId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a single custom entity */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    entityId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Requested entity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                entitySchemaId: string;
                                externalId: string | null;
                                image: {
                                    /** Format: uri */
                                    url: string;
                                    /** @enum {string} */
                                    kind: "remote";
                                } | {
                                    /** @enum {string} */
                                    kind: "s3";
                                    key: string;
                                } | unknown;
                                detailsSandboxScriptId: string | null;
                                properties: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/event-schemas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List event schemas for a custom entity schema */
        get: {
            parameters: {
                query: {
                    entitySchemaId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Event schemas for the requested entity schema */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                slug: string;
                                entitySchemaId: string;
                                propertiesSchema: {
                                    [key: string]: components["schemas"]["AppPropertyDefinition"];
                                };
                            }[];
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity schema does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an event schema for a custom entity schema */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        name: string;
                        slug?: string;
                        entitySchemaId: string;
                        propertiesSchema: {
                            [key: string]: components["schemas"]["AppPropertyDefinition"];
                        };
                    };
                };
            };
            responses: {
                /** @description Event schema was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                slug: string;
                                entitySchemaId: string;
                                propertiesSchema: {
                                    [key: string]: components["schemas"]["AppPropertyDefinition"];
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity schema does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List events for a custom entity */
        get: {
            parameters: {
                query: {
                    entityId: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Events for the requested entity */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: date-time */
                                occurredAt: string;
                                entityId: string;
                                eventSchemaId: string;
                                eventSchemaName: string;
                                eventSchemaSlug: string;
                                properties: {
                                    [key: string]: unknown;
                                };
                            }[];
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create an event for a custom entity */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        properties: {
                            [key: string]: unknown;
                        };
                        occurredAt: string;
                        entityId: string;
                        eventSchemaId: string;
                    };
                };
            };
            responses: {
                /** @description Event was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                /** Format: date-time */
                                createdAt: string;
                                /** Format: date-time */
                                updatedAt: string;
                                /** Format: date-time */
                                occurredAt: string;
                                entityId: string;
                                eventSchemaId: string;
                                eventSchemaName: string;
                                eventSchemaSlug: string;
                                properties: {
                                    [key: string]: unknown;
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Entity or event schema does not exist for this user */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/uploads/presigned": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Get a presigned upload URL for a file */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        /** @enum {string} */
                        contentType: "image/avif" | "image/gif" | "image/jpeg" | "image/png" | "image/webp";
                        fileName?: string;
                    };
                };
            };
            responses: {
                /** @description Presigned upload URL for a file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                /** Format: uri */
                                uploadUrl: string;
                                key: string;
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Presigned upload URL generation failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["InternalServerError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved views for the authenticated user */
        get: {
            parameters: {
                query?: {
                    facetId?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved views for the user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                isBuiltin: boolean;
                                facetId: string | null;
                                icon: string;
                                accentColor: string;
                                queryDefinition: {
                                    entitySchemaIds: string[];
                                };
                            }[];
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a saved view */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": {
                        icon: string;
                        name: string;
                        accentColor: string;
                        facetId?: string;
                        queryDefinition: {
                            entitySchemaIds: string[];
                        };
                    };
                };
            };
            responses: {
                /** @description Saved view was created */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                isBuiltin: boolean;
                                facetId: string | null;
                                icon: string;
                                accentColor: string;
                                queryDefinition: {
                                    entitySchemaIds: string[];
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/saved-views/{viewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a saved view */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    viewId: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Saved view was deleted */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            data: {
                                id: string;
                                name: string;
                                isBuiltin: boolean;
                                facetId: string | null;
                                icon: string;
                                accentColor: string;
                                queryDefinition: {
                                    entitySchemaIds: string[];
                                };
                            };
                        };
                    };
                };
                /** @description Request payload validation failed */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["ValidationFailedError"];
                        };
                    };
                };
                /** @description Request is unauthenticated */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["UnauthenticatedError"];
                        };
                    };
                };
                /** @description Saved view not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: components["schemas"]["NotFoundError"];
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthCheckFailedError: {
            message: string;
            /** @enum {string} */
            code: "health_check_failed";
        };
        UnauthenticatedError: {
            message: string;
            /** @enum {string} */
            code: "unauthenticated";
        };
        ValidationFailedError: {
            message: string;
            /** @enum {string} */
            code: "validation_failed";
        };
        NotFoundError: {
            message: string;
            /** @enum {string} */
            code: "not_found";
        };
        AppPropertyDefinition: components["schemas"]["AppPrimitiveProperty"] | components["schemas"]["AppArrayProperty"] | components["schemas"]["AppObjectProperty"];
        AppPrimitiveProperty: {
            /** @enum {boolean} */
            required?: true;
            /** @enum {string} */
            type: "string" | "number" | "integer" | "boolean" | "date";
        };
        AppArrayProperty: {
            /** @enum {boolean} */
            required?: true;
            /** @enum {string} */
            type: "array";
            items: components["schemas"]["AppPropertyDefinition"];
        };
        AppObjectProperty: {
            /** @enum {boolean} */
            required?: true;
            /** @enum {string} */
            type: "object";
            properties: {
                [key: string]: components["schemas"]["AppPropertyDefinition"];
            };
        };
        InternalServerError: {
            message: string;
            /** @enum {string} */
            code: "internal_error";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
