/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SchemaSearchRouteImport } from './routes/schema-search'
import { Route as IndexRouteImport } from './routes/index'

const SchemaSearchRoute = SchemaSearchRouteImport.update({
  id: '/schema-search',
  path: '/schema-search',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/schema-search': typeof SchemaSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/schema-search': typeof SchemaSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/schema-search': typeof SchemaSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/schema-search'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/schema-search'
  id: '__root__' | '/' | '/schema-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SchemaSearchRoute: typeof SchemaSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schema-search': {
      id: '/schema-search'
      path: '/schema-search'
      fullPath: '/schema-search'
      preLoaderRoute: typeof SchemaSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SchemaSearchRoute: SchemaSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
