/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTrackerSlugIndexRouteImport } from './routes/_protected/$trackerSlug/index'
import { Route as ProtectedViewsViewIdRouteImport } from './routes/_protected/views/$viewId'
import { Route as ProtectedEntitiesEntityIdRouteImport } from './routes/_protected/entities/$entityId'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTrackerSlugIndexRoute =
  ProtectedTrackerSlugIndexRouteImport.update({
    id: '/$trackerSlug/',
    path: '/$trackerSlug/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedViewsViewIdRoute = ProtectedViewsViewIdRouteImport.update({
  id: '/views/$viewId',
  path: '/views/$viewId',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedEntitiesEntityIdRoute =
  ProtectedEntitiesEntityIdRouteImport.update({
    id: '/entities/$entityId',
    path: '/entities/$entityId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/start': typeof StartRoute
  '/entities/$entityId': typeof ProtectedEntitiesEntityIdRoute
  '/views/$viewId': typeof ProtectedViewsViewIdRoute
  '/$trackerSlug/': typeof ProtectedTrackerSlugIndexRoute
}
export interface FileRoutesByTo {
  '/start': typeof StartRoute
  '/': typeof ProtectedIndexRoute
  '/entities/$entityId': typeof ProtectedEntitiesEntityIdRoute
  '/views/$viewId': typeof ProtectedViewsViewIdRoute
  '/$trackerSlug': typeof ProtectedTrackerSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/start': typeof StartRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/entities/$entityId': typeof ProtectedEntitiesEntityIdRoute
  '/_protected/views/$viewId': typeof ProtectedViewsViewIdRoute
  '/_protected/$trackerSlug/': typeof ProtectedTrackerSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start'
    | '/entities/$entityId'
    | '/views/$viewId'
    | '/$trackerSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/start'
    | '/'
    | '/entities/$entityId'
    | '/views/$viewId'
    | '/$trackerSlug'
  id:
    | '__root__'
    | '/_protected'
    | '/start'
    | '/_protected/'
    | '/_protected/entities/$entityId'
    | '/_protected/views/$viewId'
    | '/_protected/$trackerSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/$trackerSlug/': {
      id: '/_protected/$trackerSlug/'
      path: '/$trackerSlug'
      fullPath: '/$trackerSlug/'
      preLoaderRoute: typeof ProtectedTrackerSlugIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/views/$viewId': {
      id: '/_protected/views/$viewId'
      path: '/views/$viewId'
      fullPath: '/views/$viewId'
      preLoaderRoute: typeof ProtectedViewsViewIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/entities/$entityId': {
      id: '/_protected/entities/$entityId'
      path: '/entities/$entityId'
      fullPath: '/entities/$entityId'
      preLoaderRoute: typeof ProtectedEntitiesEntityIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedEntitiesEntityIdRoute: typeof ProtectedEntitiesEntityIdRoute
  ProtectedViewsViewIdRoute: typeof ProtectedViewsViewIdRoute
  ProtectedTrackerSlugIndexRoute: typeof ProtectedTrackerSlugIndexRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedEntitiesEntityIdRoute: ProtectedEntitiesEntityIdRoute,
  ProtectedViewsViewIdRoute: ProtectedViewsViewIdRoute,
  ProtectedTrackerSlugIndexRoute: ProtectedTrackerSlugIndexRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
