/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StartRouteImport } from './routes/start'
import { Route as ProtectedRouteRouteImport } from './routes/_protected/route'
import { Route as ProtectedIndexRouteImport } from './routes/_protected/index'
import { Route as ProtectedTrackingFacetSlugIndexRouteImport } from './routes/_protected/tracking/$facetSlug/index'
import { Route as ProtectedTrackingFacetSlugViewsViewIdRouteImport } from './routes/_protected/tracking/$facetSlug/views/$viewId'
import { Route as ProtectedTrackingFacetSlugEntitiesEntityIdRouteImport } from './routes/_protected/tracking/$facetSlug/entities/$entityId'

const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRouteRoute = ProtectedRouteRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedIndexRoute = ProtectedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRouteRoute,
} as any)
const ProtectedTrackingFacetSlugIndexRoute =
  ProtectedTrackingFacetSlugIndexRouteImport.update({
    id: '/tracking/$facetSlug/',
    path: '/tracking/$facetSlug/',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedTrackingFacetSlugViewsViewIdRoute =
  ProtectedTrackingFacetSlugViewsViewIdRouteImport.update({
    id: '/tracking/$facetSlug/views/$viewId',
    path: '/tracking/$facetSlug/views/$viewId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)
const ProtectedTrackingFacetSlugEntitiesEntityIdRoute =
  ProtectedTrackingFacetSlugEntitiesEntityIdRouteImport.update({
    id: '/tracking/$facetSlug/entities/$entityId',
    path: '/tracking/$facetSlug/entities/$entityId',
    getParentRoute: () => ProtectedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof ProtectedIndexRoute
  '/start': typeof StartRoute
  '/tracking/$facetSlug/': typeof ProtectedTrackingFacetSlugIndexRoute
  '/tracking/$facetSlug/entities/$entityId': typeof ProtectedTrackingFacetSlugEntitiesEntityIdRoute
  '/tracking/$facetSlug/views/$viewId': typeof ProtectedTrackingFacetSlugViewsViewIdRoute
}
export interface FileRoutesByTo {
  '/start': typeof StartRoute
  '/': typeof ProtectedIndexRoute
  '/tracking/$facetSlug': typeof ProtectedTrackingFacetSlugIndexRoute
  '/tracking/$facetSlug/entities/$entityId': typeof ProtectedTrackingFacetSlugEntitiesEntityIdRoute
  '/tracking/$facetSlug/views/$viewId': typeof ProtectedTrackingFacetSlugViewsViewIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_protected': typeof ProtectedRouteRouteWithChildren
  '/start': typeof StartRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/tracking/$facetSlug/': typeof ProtectedTrackingFacetSlugIndexRoute
  '/_protected/tracking/$facetSlug/entities/$entityId': typeof ProtectedTrackingFacetSlugEntitiesEntityIdRoute
  '/_protected/tracking/$facetSlug/views/$viewId': typeof ProtectedTrackingFacetSlugViewsViewIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start'
    | '/tracking/$facetSlug/'
    | '/tracking/$facetSlug/entities/$entityId'
    | '/tracking/$facetSlug/views/$viewId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/start'
    | '/'
    | '/tracking/$facetSlug'
    | '/tracking/$facetSlug/entities/$entityId'
    | '/tracking/$facetSlug/views/$viewId'
  id:
    | '__root__'
    | '/_protected'
    | '/start'
    | '/_protected/'
    | '/_protected/tracking/$facetSlug/'
    | '/_protected/tracking/$facetSlug/entities/$entityId'
    | '/_protected/tracking/$facetSlug/views/$viewId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ProtectedRouteRoute: typeof ProtectedRouteRouteWithChildren
  StartRoute: typeof StartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tracking/$facetSlug/': {
      id: '/_protected/tracking/$facetSlug/'
      path: '/tracking/$facetSlug'
      fullPath: '/tracking/$facetSlug/'
      preLoaderRoute: typeof ProtectedTrackingFacetSlugIndexRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tracking/$facetSlug/views/$viewId': {
      id: '/_protected/tracking/$facetSlug/views/$viewId'
      path: '/tracking/$facetSlug/views/$viewId'
      fullPath: '/tracking/$facetSlug/views/$viewId'
      preLoaderRoute: typeof ProtectedTrackingFacetSlugViewsViewIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
    '/_protected/tracking/$facetSlug/entities/$entityId': {
      id: '/_protected/tracking/$facetSlug/entities/$entityId'
      path: '/tracking/$facetSlug/entities/$entityId'
      fullPath: '/tracking/$facetSlug/entities/$entityId'
      preLoaderRoute: typeof ProtectedTrackingFacetSlugEntitiesEntityIdRouteImport
      parentRoute: typeof ProtectedRouteRoute
    }
  }
}

interface ProtectedRouteRouteChildren {
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedTrackingFacetSlugIndexRoute: typeof ProtectedTrackingFacetSlugIndexRoute
  ProtectedTrackingFacetSlugEntitiesEntityIdRoute: typeof ProtectedTrackingFacetSlugEntitiesEntityIdRoute
  ProtectedTrackingFacetSlugViewsViewIdRoute: typeof ProtectedTrackingFacetSlugViewsViewIdRoute
}

const ProtectedRouteRouteChildren: ProtectedRouteRouteChildren = {
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedTrackingFacetSlugIndexRoute: ProtectedTrackingFacetSlugIndexRoute,
  ProtectedTrackingFacetSlugEntitiesEntityIdRoute:
    ProtectedTrackingFacetSlugEntitiesEntityIdRoute,
  ProtectedTrackingFacetSlugViewsViewIdRoute:
    ProtectedTrackingFacetSlugViewsViewIdRoute,
}

const ProtectedRouteRouteWithChildren = ProtectedRouteRoute._addFileChildren(
  ProtectedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ProtectedRouteRoute: ProtectedRouteRouteWithChildren,
  StartRoute: StartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
