import {
	ArrowRight,
	ArrowUpDown,
	Book,
	BookCopy,
	BookHeart,
	BookImage,
	BookMarked,
	BookOpen,
	Bookmark,
	Building2,
	Check,
	ChevronDown,
	ChevronLeft,
	ChevronRight,
	ChevronUp,
	Circle,
	CircleCheck,
	CircleX,
	ClipboardList,
	Clapperboard,
	Disc3,
	Dumbbell,
	Film,
	Folder,
	Folders,
	FolderKanban,
	Gamepad2,
	Grid2X2,
	GripVertical,
	Globe,
	Headphones,
	Heart,
	HeartPulse,
	House,
	Image,
	Inbox,
	Joystick,
	Layers3,
	Library,
	List,
	ListVideo,
	LogOut,
	Menu,
	Mic,
	Monitor,
	MonitorPlay,
	Moon,
	MoreHorizontal,
	Music2,
	PanelLeft,
	Plus,
	Podcast,
	Radio,
	RotateCcw,
	Ruler,
	Search,
	SearchX,
	Settings,
	SlidersHorizontal,
	Sparkles,
	SquarePlay,
	Star,
	Sun,
	Table2,
	Tags,
	Tv,
	UserCircle,
	Users,
	X,
	Zap,
} from "lucide-react-native";
import type { LucideIcon } from "lucide-react-native";
import { styled } from "nativewind";
import type { ComponentProps, ComponentType } from "react";

type StyledIcon = ComponentType<ComponentProps<LucideIcon> & { className: string }>;

const iconColorMapping = {
	className: { target: "style", nativeStyleMapping: { color: "color" } },
} as const;

function createStyledIcon(Icon: LucideIcon) {
	return styled(Icon, iconColorMapping) as StyledIcon;
}

const rawIconRegistry: Record<string, LucideIcon> = {
	x: X,
	tv: Tv,
	sun: Sun,
	zap: Zap,
	mic: Mic,
	tags: Tags,
	star: Star,
	book: Book,
	menu: Menu,
	film: Film,
	moon: Moon,
	plus: Plus,
	list: List,
	home: House,
	house: House,
	image: Image,
	inbox: Inbox,
	check: Check,
	heart: Heart,
	ruler: Ruler,
	users: Users,
	radio: Radio,
	globe: Globe,
	grid: Grid2X2,
	table: Table2,
	music: Music2,
	logout: LogOut,
	search: Search,
	folder: Folder,
	"disc-3": Disc3,
	folders: Folders,
	monitor: Monitor,
	podcast: Podcast,
	library: Library,
	user: UserCircle,
	"music-2": Music2,
	settings: Settings,
	joystick: Joystick,
	sparkles: Sparkles,
	dumbbell: Dumbbell,
	bookmark: Bookmark,
	"search-x": SearchX,
	"circle-x": CircleX,
	"layers-3": Layers3,
	"book-copy": BookCopy,
	"book-open": BookOpen,
	"gamepad-2": Gamepad2,
	headphones: Headphones,
	"book-heart": BookHeart,
	"book-image": BookImage,
	"building-2": Building2,
	"list-video": ListVideo,
	"rotate-ccw": RotateCcw,
	"panel-left": PanelLeft,
	"chevron-up": ChevronUp,
	"arrow-right": ArrowRight,
	"book-marked": BookMarked,
	"play-square": SquarePlay,
	"square-play": SquarePlay,
	"heart-pulse": HeartPulse,
	clapperboard: Clapperboard,
	"chevron-down": ChevronDown,
	"chevron-left": ChevronLeft,
	"circle-check": CircleCheck,
	"monitor-play": MonitorPlay,
	"arrow-up-down": ArrowUpDown,
	"chevron-right": ChevronRight,
	"folder-kanban": FolderKanban,
	"grip-vertical": GripVertical,
	"clipboard-list": ClipboardList,
	"more-horizontal": MoreHorizontal,
	"sliders-horizontal": SlidersHorizontal,
};

export const iconRegistry = Object.fromEntries(
	Object.entries(rawIconRegistry).map(([name, Icon]) => [name, createStyledIcon(Icon)]),
) as Record<string, StyledIcon>;

const FallbackIcon = createStyledIcon(Circle);

export function AppIcon(props: { name: string; className: string; size?: number }) {
	const Icon = iconRegistry[props.name] ?? FallbackIcon;
	return <Icon className={props.className} size={props.size ?? 16} strokeWidth={1.7} />;
}
